export const USER_LOGIN_PROGRESS = "USER_LOGIN_PROGRESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const ADD_EMPLOYEES_PROGRESS = "ADD_EMPLOYEES_PROGRESS";
export const ADD_EMPLOYEES_SUCCESS = "ADD_EMPLOYEES_SUCCESS";

export const GET_EMPLOYEES_PROGRESS = "GET_EMPLOYEES_PROGRESS";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";

export const UPDATE_PROFILE_PROGRESS = "UPDATE_PROFILE_PROGRESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const ADD_SALARIES_PROGRESS = "ADD_SALARIES_PROGRESS";
export const ADD_SALARIES_SUCCESS = "ADD_SALARIES_SUCCESS";

export const GET_SALARIES_PROGRESS = "GET_SALARIES_PROGRESS";
export const GET_SALARIES_SUCCESS = "GET_SALARIES_SUCCESS";

export const UPDATE_SALARY_PROGRESS = "UPDATE_SALARY_PROGRESS";
export const UPDATE_SALARY_SUCCESS = "UPDATE_SALARY_SUCCESS";

export const USER_LOGOUT_PROGRESS = "USER_LOGOUT_PROGRESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
